export enum ApiTags {
  LISTING_CATEGORIES = "LISTING_CATEGORIES",
  LISTING_TYPE_OF_PLACE = "LISTING_TYPE_OF_PLACE",
  USER = "USER",
  CURRENT_USER = "CURRENT_USER",
  CURRENT_LISTING = "CURRENT_LISTING",
  VERIFIED_LISTINGS = "VERIFIED_LISTINGS",
  LISTING = "LISTING",
  USER_LISTINGS = "USER_LISTINGS",
}
