export const ActionTypes = {
  SET_FORM_STEP: "SET_FORM_STEP",
  SET_SELECTED_CATEGORIES: "SET_SELECTED_CATEGORIES",
  SET_SELECTED_TYPE_OF_PLACE: "SET_SELECTED_TYPE_OF_PLACE",
  SET_SELECTED_CORDINATES: "SET_SELECTED_CORDINATES",
  SET_AMOUT_OF_GUESTS: "SET_AMOUT_OF_GUESTS",
};
